Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
correct_transcript_bad(grades)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [43mcorrect_transcript_bad[49m[43m([49m[43mgrades[49m[43m)[49m

Cell [0;32mIn[6], line 2[0m, in [0;36mcorrect_transcript_bad[0;34m(grades)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mcorrect_transcript_bad[39m(grades):
[0;32m----> 2[0m     [38;5;28;01mfor[39;00m course [38;5;129;01min[39;00m grades:
[1;32m      3[0m         [38;5;66;03m#grades[course] is a grade, like "B+" or "A". We [39;00m
[1;32m      4[0m         [38;5;66;03m#are checking whether grades[course] is "A" –æ—Ä "–ê+"[39;00m
[1;32m      5[0m         [38;5;28;01mif[39;00m grades[course] [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [[38;5;124m"[39m[38;5;124mA[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mA+[39m[38;5;124m"[39m]:
[1;32m      6[0m             [38;5;28;01mdel[39;00m grades[course]

[0;31mRuntimeError[0m: dictionary changed size during iteration

